# markov chain

In [2]:
import torch 

In [9]:
s0 = current_state = [0,1,0]
s0 = torch.tensor(s0,dtype=torch.float)

probability_transition_matrix = torch.tensor([
    # V bull V bear V stagnent
    [.9 , .75 , .025], # bull
    [.15 , .8 , .05],  # bear
    [.25, .25  , .5]   # stagnent

],dtype=torch.float)
number_of_iterations = 5
print(f"________________________iteration {0}_____________________________")
print(s0)
for i in range(5):
  
    s0 = torch.matmul(probability_transition_matrix,s0)
    print(f"________________________iteration {i+1}_____________________________")
    print(s0)
    print(f"\n")

________________________iteration 0_____________________________
tensor([0., 1., 0.])
________________________iteration 1_____________________________
tensor([0.7500, 0.8000, 0.2500])


________________________iteration 2_____________________________
tensor([1.2812, 0.7650, 0.5125])


________________________iteration 3_____________________________
tensor([1.7397, 0.8298, 0.7678])


________________________iteration 4_____________________________
tensor([2.2073, 0.9632, 1.0263])


________________________iteration 5_____________________________
tensor([2.7346, 1.1530, 1.3058])


